# 后台环境设置 dev-测试环境（不发送短信及邮件） normal-正式环境
appEnv = "normal"

DBHost = "localhost"
DBPort = "5432"
DBUser = "postgres"
DBPassword = "xxx"
DBName = "test"
DBNameTest = "healthMgrTest"

fileUploadPath = "/static/"

serverHost="http://localhost"
serverPort="80"
