# 后台环境设置 dev-测试环境（不发送短信及邮件） normal-正式环境
appEnv = "normal"
DBHost = "localhost"
DBPort = "5432"
DBUser = "cjwddz"

DBPassword = "imjia123"
DBName = "my-site"

staticPath = "/home/cjwddz/桌面/git-project/golang-web/static"
Path_Upload_pic = "/home/cjwddz/桌面/git-project/golang-web/upload_pic"
Path_Upload_file = "/home/cjwddz/桌面/git-project/golang-web/upload_files"

serverHost="http://localhost"
serverPort="80"
