# 后台环境设置 dev-测试环境（不发送短信及邮件） normal-正式环境
appEnv = "normal"
# 数据库
DBHost = "localhost"
DBPort = "5432"
DBUser = "postgres"
DBPassword = "pwd"
DBName = "dbName"
DBNameTest = "dbName-test"
DBDriver = "postgres"

# 日志
logCache = 100
## 最大日志间隔,单位为秒
logInterval = 10
# 路径
staticPath = "./workdir/static"
picturePath = "./workdir/static/pic"
filePath = "./workdir/static/file"
# 服务器
serverHost="http://localhost"
serverPort="80"

# redis
RedisHost = "localhost"
RedisPort = "6379"
RedisPassword = "pwd"
