# 后台环境设置 dev-测试环境（不发送短信及邮件） normal-正式环境
appEnv = "normal"
DBHost = "www.cjwddz.cn"
DBPort = "5432"
DBUser = "ubuntu"

DBPassword = "imjia123"
DBName = "my-site"


staticPath = "./workdir/static"
Path_Upload_pic = "./workdir/static/upload_pic"
Path_Upload_file = "./workdir/static/upload_files"

serverHost="http://localhost"
serverPort="80"
