# 后台环境设置 dev-测试环境（不发送短信及邮件） normal-正式环境
appEnv = "normal"
DBHost = "localhost"
DBPort = "5432"
DBUser = "postgres"

DBPassword = "imjia123"
DBName = "my_site"

staticPath = "/static"
fileUploadPath = "E:/go-web/upload_files"

serverHost="http://localhost"
serverPort="80"
