# 后台环境设置 dev-测试环境（不发送短信及邮件） normal-正式环境
appEnv = "normal"
DBHost = "localhost"
DBPort = "5432"
DBUser = "postgres"

DBPassword = "xxxxx"
DBName = "my-site"

staticPath = "./workdir/static"
Path_Upload_pic = "./workdir/static/upload_pic"
Path_Upload_file = "./workdir/static/upload_files"

serverHost="http://localhost"
serverPort="80"
